---
title: "260-2019-02-26-exam-2-review"
author: "Rick Gilmore"
date: "`r Sys.time()`"
bibliography: bib/bibliography.bib
output:
  ioslides_presentation:
    css: css/ioslides.css
    incremental: no
    transition: default
    widescreen: yes
  pdf_document:
    latex_engine: xelatex
---

## Neuroanatomy

- [Hindbrain, midbrain, forebrain & ventricular landmarks]()
- [Autonomic vs. somatic]()
- [Sympathetic vs. parasympathetic]() nervous system

## Cellular neuroscience

- [Glia]()
- [Neuronal anatomy]()

## Neurophysiology

- [Resting potential -- what & why]()
    - $[K^+]$ story (where concentrated, direction of flow)
    + $[Na^+]$ story (where concentrated, direction of flow)
- [Action potential and propagation -- how & why]()
- [Steps leading to neurotransmitter release]()

## Neurochemistry

- Neurotransmitter types
    - [Amino acids](), especially Glutamate and GABA
    - [Acetylcholine]()
    - [Monoamines]()

## Neurochemistry

- Anatomy (where released) and function
- Receptor types: [ionotropic vs. metabotropic]()
- [Inactivation mechanisms & rationale]()
- [EPSPs & IPSPs]()

## [Hormones]()

- [Behaviors under hormonal influence]()
- [Anatomy: Where released]()
- [Direct (posterior pituitary) vs. indirect (anterior) release]()
- [Responses to threat/challenge]()
- [Milk letdown reflex]()

## Brain evolution

- Emergence of complex nervous systems
- [Comparing vertebrate brains]()
- [Patterns of brain/body mass across vertebrates]()
- [Human brains vs. other animals]()

<!-- ## Brain development -->

<!-- - [Neurulation](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#16) -->
<!-- - [Prenatal vs. postnatal](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#14) -->
<!-- - Examples of [progressive](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#33) & [regressive](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#36) patterns -->
<!-- - [Cortical thickness](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-09-development-II.html#35) -->
<!-- - [Myelination](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-09-development-II.html#21) -->