---
title: "260-2017-12-06-exam-4-study-guide"
author: Rick Gilmore
date: "`r Sys.time()`"
bibliography: bib/bibliography.bib
output:
  ioslides_presentation:
    css: css/ioslides.css
    incremental: no
    transition: default
    widescreen: yes
  pdf_document:
    latex_engine: xelatex
---

## Prelude

<iframe width="560" height="315" src="https://www.youtube.com/embed/huOT6zCgZEU" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>

## Today's topics

- Review for Exam 4
    - Thursday, May 2, <span class="red">4:40-6:30p, 112 Buckhout</red>
- The Cerebral Symphony
    
## History

- Descartes thought `____` about the `____`
- Fluid from the cerebral ventricles was once thought to `____`

## Methods

- Single unit recordings have `____` spatial and `____` temporal resolution.
- EEG has`____` spatial and `____` temporal resolution.
- Single unit recordings measure `____`; EEG measures `____`.

## Anatomy

- Directional terms, slices
    + In the human forebrain `____` and superior overlap.
- Gross
    + The `____` means "little brain" in Latin; it's located adjacent to `_____`.
    + The `____` and `____` in the midbrain release dopamine
    + The `____` controls endocrine and ANS activity.
    
----

- Gross anatomy
    + The insula is located deep inside the `____`.
    + Forebrain/midbrain/hindbrain
    + ventricles/CSF, meninges, blood supply
    + Gyri/sulci
    + lobes, insula/insular cortex
    + gray/white matter
    
## Cellular anatomy

- Neurons receive most of their input on the `____` and `____`.
- Gray matter is made of `____`; white matter is made of `____`.
    
## Neurophysiology

- Resting potential
    + In neuron at rest, `____` inside is greater than outside; What force(s) `____` push [Na+] inward?
- Ca++ influx is involved in `____`, `____`, and `____`.
- EPSP/IPSPs are `____` than action potentials

----

- Nodes of Ranvier contain lots of `____`gated channels
- The *absolute refractory period* occurs when voltage-gated Na+ channels `____`
- Action potential phases, causes/components
- Synaptic transmission
    + EPSPs, IPSPs
- Synaptic plasticity, LTP, NMDA receptors

## Neurochemistry

- Big Three -- Glu, GABA, ACh
- Neuromodulators -- DA, NE, 5-HT
- Hormones
    + Oxytocin, vasopressin are released from `____`.
- Can we readily measure neurotransmitter levels in the brain?

## Evolution and development

- There is a "mammalian" brain plan (True/False)

## Emotion

- The `____` lobe contains the amygdala
- Pleasure/reward systems, key brain areas and neurotransmitter(s)
- Fear, stress in behavior and brain
    + What's more important to measure, objective stress or perceived stress?

## Perception and Action

- Sensory fibers enter the (dorsal/ventral) spinal cord. Motor fibers exit from the (dorsal/ventral) spinal cord.
- Parietal lobe contains `____` cortex.
- Photoreceptor cells release more neurotransmitter in (darkness/light)
- Can't see reddish-green because long ("red") and medium ("green") cones `____`

---

- Areas of cortex devoted to moving fingers, tongue are (large/small)
- Most retinal ganglion cells project to the `____`.
- Sound direction is signaled by `____`.
- Minty flavors taste `cool' because...
- Topographic maps: somatosensation, audition, vision

---

- Perceiving what vs. where: vision, somatosensation
- Functional segregation: examples of
- Receptive fields: how size varies with perceptual sensitivity 

## Memory

- Long-term Potentiation (LTP) involves neuron A's connection to neuron B `____`
- NMDA receptor opens when sending cell `____` and receiving cell `____`.
- Amnesia
    + `____` is impaired; `____` is spared.
- NMDA receptors and Hebbian learning
- Hippocampus size and memory demands

