---
title: "Schedule"
---

*[B&W](http://behavioralneuroscience8e.com/) refers to the Breedlove & Watson text. Assignments are given in chapter:pages format, e.g., 1:2-19 means read Chapter 1, pages 2-19.*

## Week 1, January 7 - 11

### Tuesday, January 8

- Topics
    - Introduction to the course
    - What is a system?
- Assignments
    - Read: [B&W](http://behavioralneuroscience8e.com/) 1:2-19.
    - Review: <https://en.wikipedia.org/wiki/Systems_theory>
    - Review: <http://www.columbia.edu/cu/psychology/courses/1010/mangels/neuro/history/history.html>.
    - Scan: <https://faculty.washington.edu/chudler/hist.html>
- Materials
    - Lecture notes | [HTML slides](lectures/260-2019-01-08-intro.html) |

### Thursday, January 10

- Topics
    - History of neuroscience
    - Levels of analysis
    - Neuroscience methods I
- Assignments
    - Read: [B&W](http://behavioralneuroscience8e.com/) 1:1-21; 2:51-57; 3:88-92.
    - Watch: [Beautiful 3-D Brain Scans Show Every Synapse](https://youtu.be/nvXuq9jRWKE)
    - Optional:
        - [Grillner, Kozlov, Kotaleski (2005)](http://www.ncbi.nlm.nih.gov/pubmed/16146688)
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-01-10-history-levels-methods.html) |

---

## Week 2, January 14 - 18

### Tuesday, January 15

- Topics
    - Neuroscience methods II.
- Assignments
    - Read: [B&W](http://behavioralneuroscience8e.com/) 2:51-57; 3:88-92.
    - Watch: [Magnetic Resonance Imaging Explained](https://youtu.be/MiL0wCZr0Mw)
    - Optional: <https://en.wikibooks.org/wiki/Cognitive_Psychology_and_Cognitive_Neuroscience/Behavioural_and_Neuroscience_Methods>.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-01-15-functional-methods.html) |

### Thursday, January 17

- Topics
    - Neuroanatomy I
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/): 2:36-51.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-01-17-anatomy-I.html) |

---

## Week 3, January 21 - 25

### Tuesday, January 22

- Topics
    - Neuroanatomy II
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/): 2:36-51.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-01-22-anatomy-II.html) |

### Thursday, January 24

- Topics
    - **Quiz 1**
    - Neuroanatomy III
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-01-24-anatomy-III.html) |

---

## Week 4, January 28 - February 1

### Tuesday, January 29

- Topics
    - Cells of the nervous system
    - How nerve cells compute (Neurophysiology I)
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/): 2:25-35.
    - Read [B&W](http://behavioralneuroscience8e.com/): 3:61-66.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-01-29-cells.html) |

### Thursday, January 31

**NO CLASS. UNIVERSITY CLOSURE**
<!-- - Topics -->
<!--     - Neurophysiology II -->
<!-- - Assignments -->
<!--     - Read: [B&W](http://behavioralneuroscience8e.com/): 3:66-87. -->
<!--     - Watch: Video about membrane potentials <https://www.youtube.com/embed/PtKAeihnbv0> -->
<!--  - Materials -->
<!--     - Lecture notes. | [HTML slides](lectures/260-2019-01-31-neurophys-II.html) | -->
   
---

## Week 5, February 4 - 8

### Tuesday, February 5

- Topics
    - Neurophysiology II
- Assignments
    - Read: [B&W](http://behavioralneuroscience8e.com/): 3:66-87.
    - Watch: Video about membrane potentials <https://www.youtube.com/embed/PtKAeihnbv0>
 - Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-01-31-neurophys-II.html) |
   
<!-- - Topics -->
<!--     - Neurophysiology III -->
<!--     - Exam 1 Review -->
<!-- - Assignments -->
<!--     <!-- - Read [B&W](http://behavioralneuroscience8e.com/) 3:59-69 -->
 <!-- - Materials -->
 <!--    - Lecture notes. | [HTML slides]() | -->

### Thursday, February 7

- Topics
    - Neurophysiology III
    - Exam 1 Review
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 3:59-69
- Materials
   - Lecture notes. | [HTML slides](lectures/260-2019-02-07-neurophys-III.html) |
   - [Study guide](lectures/260-2019-02-07-exam-1-review.html)
 
<!-- - Topics -->
<!--     - **Exam 1**. -->

---

## Week 6, February 11 - 15

### Tuesday, February 12

- Topics
    - ~~**Exam 1**~~.

<!-- - Topics -->
<!--     - Neurochemistry I -->
<!-- - Assignments -->
<!--     -  Read [B&W](http://behavioralneuroscience8e.com/) 3:79-85. -->
<!--     -  Read [B&W](http://behavioralneuroscience8e.com/) 4:95-103. -->
<!-- - Materials -->
<!--     - Lecture notes. | [HTML slides]() | -->

### Thursday, February 14

- Topics
    - Neurochemistry I
- Assignments
    -  Read [B&W](http://behavioralneuroscience8e.com/) 3:79-85.
    -  Read [B&W](http://behavioralneuroscience8e.com/) 4:95-103.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-02-14-neurochem-I.html) |

<!-- - Topics -->
<!--     - Neurochemistry II -->
<!--     - Hormones and the brain -->
<!-- - Assignments -->
<!--     - Read [B&W](http://behavioralneuroscience8e.com/) 4:101-112. -->
<!--     - Read [B&W](http://behavioralneuroscience8e.com/) 5:131-137; 5:143-155. -->
<!-- - Materials -->
<!--     - Lecture notes. | [HTML slides]() | -->

---

## Week 7, February 18 - 22

### Tuesday, February 19

- Topics
    - Neurochemistry II
    - Hormones and the brain
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 4:101-112.
    - Read [B&W](http://behavioralneuroscience8e.com/) 5:131-137; 5:143-155.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-02-19-neurochem-II.html) |

<!-- - Topics -->
<!--     - **Quiz 2**.  -->
<!--     - Exam 1 returned. -->
<!--     - **Blog post 1 (of 3) due**. | [Assignment details](blog-assignment.html) | -->
<!-- <!-- - Materials -->
<!-- <!--     - Lecture notes. | [HTML slides]() | --> 

### Thursday, February 21

- Topics
    - Wrap-up on neurochemistry
    - **Quiz 2**. 
    - **Blog post 1 (of 3) due**. | [Assignment details](blog-assignment.html) |
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-02-21-hormones.html) |


<!-- - Topics -->
<!--     - Evolution of the human brain. -->
<!-- - Assignments -->
<!--     <!-- - Read [Hofman 2014](http://www.frontiersin.org/Journal/Abstract.aspx?s=742&name=neuroanatomy&ART_DOI=10.3389/fnana.2014.00015). -->
<!--     - Read [B&W](http://behavioralneuroscience8e.com/) 6:163-191. -->
<!-- <!-- - Materials -->
<!-- <!--     - Lecture notes. | [HTML slides]() | -->

---
    
## Week 8, February 25 - March 1

### Tuesday, February 26

- Topics
    - Evolution of the human brain.
- Assignments
    <!-- - Read [Hofman 2014](http://www.frontiersin.org/Journal/Abstract.aspx?s=742&name=neuroanatomy&ART_DOI=10.3389/fnana.2014.00015). -->
    - Read [B&W](http://behavioralneuroscience8e.com/) 6:163-191.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-02-26-evolution.html) |
    - Exam 2 [study guide](lectures/260-2019-02-26-exam-2-review.html)
<!-- - Topics -->
<!--     - Development of the brain -->
<!--     - Review for Exam 2 -->
<!-- - Assignments -->
<!--     - Read [B&W](http://behavioralneuroscience8e.com/) 7:193-210. -->
<!-- <!-- - Materials -->
<!-- <!--     - Lecture notes. | [HTML slides]() | -->

### Thursday, February 28

- Topics
    - **Exam  2**.

---

## Spring Break, March 4 - 8

**NO CLASSES**

---

## Week 9, March 11 - 15

### Tuesday, March 12

- Topic
    - Psychopathology I: Depression & Bipolar disorder
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 16:514-523.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-03-12-depression-bipolar.html) |
    
### Thursday, March 14

- Psychopathology II: Schizophrenia.
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 16:499-514.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-03-14-schizophrenia.html) |

---

## Week 10, March 18 - 22

#### Tuesday, March 19

- Topics
    - Emotion
    - Happiness & reward
    - Fear & stress
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 15:467-485; 15:488-497.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-03-19-emotion.html) |

### Thursday, March 21

- Topics
    - **Quiz 3**.
    - Exam 2 returned. | [HTML slides](lectures/260-2019-03-21-exam-2-discuss.html) |

---

## Week 11, March 25 - 29

### Tuesday, March 26

- Topics
    - Sensory systems
    - Somatosensation
    - Pain
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 8:229-262.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-03-26-sensation.html) |

### Thursday, March 28

- Topics
    - Action
- Assignments
    - **Blog post #2 (of 3) due**. | [Assignment details](blog-assignment.html) |
    - Read [B&W](http://behavioralneuroscience8e.com/) 11:337-347.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-03-28-action.html) |
   
---

## Week 12, April 1 - 5

### Tuesday, April 2

- Topics
    - Action II
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 11:347-368.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-04-02-action-II.html) |

### Thursday, April 4

- Vision
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 10:301-321.
- Materials
    - Lecture notes. | [HTML slides](lectures/260-2019-04-04-vision.html) |

---

## Week 13, April 8 - 12

### Tuesday, April 9

- Topics
    - Vision II
    - Review for Exam 3.
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 10:321-330.

### Thursday, April 11

- Topics
    - **Exam 3**.

---

## Week 14, April 15 - 19

### Tuesday, April 16

<!-- Courtney wants to lecture -->

- Topics
    - Learning & memory
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 17:535-552.
- **Papers or blog post #3 (of 3) due**. | [Blog assignment details](blog-assignment.html) | [Paper assignment details](paper-assignment.html) |
<!-- - Materials -->
<!--     - Lecture notes. | [HTML slides]() | -->

### Thursday, April 18

- Topics
    - Learning & memory II
    - **Quiz 4**.
    - Exam 3 returned.
- Assignments
    - Read [B&W](http://behavioralneuroscience8e.com/) 17:552-565.
<!-- - Materials -->
<!--     - Lecture notes. | [HTML slides]() | -->

---

## Week 15, April 22 - 26

### Tuesday, April 23

- Topics
    - The Cerebral Symphony
    - Speed of nervous system conduction lab

### Thursday, April 25

<!-- Courtney out -->

- Topics
    - Review for Exam 4

---
    
## Finals Week, April 29 - May 3

### Thursday, May 2, 4:40-6:30p, 112 Buckhout

- Exam 4
