---
title: "260-2019-02-26-exam-2-review"
author: "Rick Gilmore"
date: "`r Sys.time()`"
bibliography: bib/bibliography.bib
output:
  ioslides_presentation:
    css: css/ioslides.css
    incremental: no
    transition: default
    widescreen: yes
  pdf_document:
    latex_engine: xelatex
---

## Neuroanatomy

- [Hindbrain, midbrain, forebrain & ventricular landmarks]()
- [Autonomic vs. somatic]()
- [Sympathetic vs. parasympathetic]() nervous system

## Cellular neuroscience

- [Glia]()
- [Neuronal anatomy]()

## Neurophysiology

- [Resting potential -- what & why](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-01-29-cells.html#87) and [this](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-01-31-neurophys-II.html#35)
    - $[K^+]$ story (where concentrated, direction of flow)
    + $[Na^+]$ story (where concentrated, direction of flow)
    - [Summary](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-07-neurophys-III.html#6)
- [Action potential and propagation -- how & why](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-01-31-neurophys-II.html#38)
- [Steps leading to neurotransmitter release](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#6) and [this summary figure](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#26)

## Neurochemistry

- Neurotransmitter types
    - [Amino acids](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#27), especially [Glutamate](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#28) and [GABA](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#30)
    - [Acetylcholine](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#33)
    - [Monoamines](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-19-neurochem-II.html#12)

## Neurochemistry

- Anatomy (where released) and function
- Receptor types: [ionotropic vs. metabotropic](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#12)
- [Inactivation mechanisms & rationale](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#16)
- [EPSPs & IPSPs](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-14-neurochem-I.html#15)

## [Hormones](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-19-neurochem-II.html#46)

- [Behaviors under hormonal influence](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-19-neurochem-II.html#50)
- [Anatomy: Where released](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-21-hormones.html#16)
- [Direct (posterior pituitary) vs. indirect (anterior) release](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-21-hormones.html#20)
- [Responses to threat/challenge](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-21-hormones.html#26)
- [Milk letdown reflex](https://psu-psychology.github.io/psych-260-2019-spring/lectures/260-2019-02-21-hormones.html#30)

## Brain evolution

- Emergence of complex nervous systems
- [Comparing vertebrate brains]()
- [Patterns of brain/body mass across vertebrates]()
- [Human brains vs. other animals]()

<!-- ## Brain development -->

<!-- - [Neurulation](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#16) -->
<!-- - [Prenatal vs. postnatal](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#14) -->
<!-- - Examples of [progressive](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#33) & [regressive](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-06-development.html#36) patterns -->
<!-- - [Cortical thickness](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-09-development-II.html#35) -->
<!-- - [Myelination](https://psu-psychology.github.io/psych-260-2017-fall/lectures/260-2017-10-09-development-II.html#21) -->